import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cinzel, Inter, Bellefair } from "next/font/google";
import localFont from "next/font/local";
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import "../globals.css";

const locales = ['en', 'fr', 'sv'];

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale?: string}>;
}) {
  const resolvedParams = await params;
  const locale = resolvedParams?.locale ?? 'en';

  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages} locale={locale}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const cinzel = Cinzel({
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const inter = Inter({
    subsets: ["latin"],
});

export const bellefair = Bellefair({
    subsets: ["latin"],
    weight: ["400"],
});

export const nordic = localFont({
  src:"../../public/fonts/Nordic.ttf"
})