services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    ports:
      - "9090:9090"
    networks:
      - otta
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false

    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - otta
    restart: unless-stopped

#   elasticsearch:
#     image: elasticsearch:8.11.0
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#     ports:
#       - "9200:9200"

  # logstash:
  #   image: logstash:8.11.0
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5044:5044"
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: kibana:8.11.0
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - nodejs
      - front
    networks:
      - otta
    restart: unless-stopped

  nodejs:
    build: ./nodejs
    container_name: nodejs
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - otta
    restart: unless-stopped

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - otta
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: front
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    env_file:
      - ./.env
    networks:
      - otta
    restart: unless-stopped

volumes:
  db_data:
    name: db_data
  grafana_data:
  prometheus_data:

networks:
  otta:
    driver: bridge
