services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - nodejs
    networks:
      - otta
    restart: unless-stopped
    labels:
      collect_logs: "true"

  nodejs:
    build: ./nodejs
    container_name: nodejs
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
        mysql:
            condition: service_healthy
        # logstash:
        #     condition: service_healthy
    networks:
      - otta
    restart: unless-stopped
    volumes: # only for dev purpose gotta remove later
      - ./nodejs/src:/app/src
      - ./nodejs/databases:/app/databases
      - /app/node_modules
    labels:
      collect_logs: "true"
  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - otta
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 10
    labels:
      collect_logs: "true"
  front:
    build: ./front
    container_name: front
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    networks:
      - otta
    restart: unless-stopped
    labels:
      collect_logs: "true"
    volumes:
      - ./front:/app
      - /app/node_modules  # protège node_modules

volumes:
  db_data:
    name: db_data
  elastic_data:
    name: elastic_data

networks:
  otta:
    driver: bridge
  # kibana-setup:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - otta
  #   restart: "no"
  #   entrypoint: ["bash", "-c", "sleep 10 && curl -s -X POST -u elastic:$$ELASTIC_PASSWORD http://elasticsearch:9200/_security/service/elastic/kibana/credential/token/kibana_token"]
  #   env_file:
  #     - ./.env
