global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nodejs"
    metrics_path: /metrics
    static_configs:
      - targets: ["nodejs:3000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]